### ISSUE TITLE
Error when run sh butgg.sh --setup [: Ubuntu: unexpected operator

### ISSUE THREAD

**Issue by mbrother2** [mbrother2/backuptogoogle#1]
##### Detail log:
```
[ 15/11/2019 10:07:11 ] ---
[ 15/11/2019 10:07:12 ] Cheking network...
[ 15/11/2019 10:07:12 ] Connect Github successful
[ 15/11/2019 10:07:12 ] Connect Google successful
[ 15/11/2019 10:07:12 ] Checking OS...
[ 15/11/2019 10:07:12 ] OS supported
[ 15/11/2019 10:07:12 ] Downloading script cron file from github...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 6486 100 6486 0 0 16659 0 --:--:-- --:--:-- --:--:-- 16630
butgg.sh: 39: [: Ubuntu: unexpected operator
butgg.sh: 39: [: Ubuntu: unexpected operator
butgg.sh: 1: butgg.sh: md5: not found
butgg.sh: 45: [: fd4ed0c766ca96af93cd15fc1eda4bc6: unexpected operator
[ 15/11/2019 10:07:12 ] -e \e[31m[CHECKS][FAIL]\e[0m Can not verify md5sum for file cron_backup.sh. Exit!
```

**Comment by mbrother2** [comment]
Case of https://github.com/yohukm with Ubuntu 16.04.6

**Comment by mbrother2** [comment]
I detected problem. Because Ubuntu system links sh shell to dash shell( https://wiki.ubuntu.com/DashAsBinSh ). I will be commit new version asap.

**Comment by mbrother2** [comment]
Hi,

I split the script to support Linux system and BSD system:
For Linux please use commands:
```
curl -o butgg.bash https://raw.githubusercontent.com/mbrother2/backuptogoogle/master/butgg.bash
bash butgg.bash --setup
```
For BSD please use commands:
```
curl -o butgg.sh https://raw.githubusercontent.com/mbrother2/backuptogoogle/master/butgg.sh
sh butgg.sh --setup
```
Please let me know if you get any trouble.

**Comment by GarinZeroOne** [comment]
I get this error when i run bash butgg.bash --setup on ubuntu server 18.04

> [CHECKS][FAIL] Can not verify md5 for file butgg.bash. Exit!

**Comment by yohukm** [comment]
thank for  update  
the script very help

**Comment by mbrother2** [comment]
@GarinZeroOne I updated md5 of butgg.bash. Please try again.
@yohukm thank you for your feedback. Please open new issue if you get any trouble.

**Comment by qasimmughal0** [comment]
Hi All,
I'm facing an error during verify the GDrive app on google account.
Can anyone guide me on how can I fix that? I'm using windows platform
![Google Drive](https://user-images.githubusercontent.com/57908730/69065236-41b8bf00-0a41-11ea-8f9d-1740621cb144.PNG)

**Comment by mbrother2** [comment]
@qasimmughal0 
You must complie gdrive with your Google credential, you can create Google credential here:
https://github.com/mbrother2/backuptogoogle/wiki/Create-own-Google-credential-step-by-step
Then complie gdrive on Windows by PowerShell with tutorial:
https://github.com/gdrive-org/gdrive/issues/426

Hmm, If need, I can complie one gdrive bin for your platform, Which Windows OS do you use?

**Comment by qasimmughal0** [comment]
@mbrother2 
Thanks for your reply.
Yes, I need GDrive for windows platform. I'm using windows server 2012 and 2016.
That'll be great help.

**Comment by mbrother2** [comment]
@qasimmughal0 
This is gdrive bin I complied on Windows 2012 R2, please try:
[gdrive.zip](https://github.com/mbrother2/backuptogoogle/files/3862967/gdrive.zip)

**Comment by qasimmughal0** [comment]
@mbrother2 
I've tried now I'm getting a new error during copy files on Google Drive.

Failed to get file: Get https://www.googleapis.com/drive/v3/files/1ShTrMEb9QZY1jsJ17aOHvIva3pApl7zE?alt=json&fields=appP
roperties: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."

**Comment by mbrother2** [comment]
@qasimmughal0 
Please reset your Google token by remove file token_v2.json and try again.

**Comment by qasimmughal0** [comment]
@mbrother2 
Can you guide me how can I reset?

**Comment by mbrother2** [comment]
@qasimmughal0 
You can read here:
https://github.com/gdrive-org/gdrive/issues/317

**Comment by qasimmughal0** [comment]
@mbrother2 
But I don't know where is %appdata%\.gdrive\token_v2.json directory in windows.
Can you tell me where it should be in the windows platform?

**Comment by mbrother2** [comment]
@qasimmughal0 
You can search .gdrive folder on your server. File token_v2.json locate in .gdrive folder

**Comment by qasimmughal0** [comment]
@mbrother2 
Thanks, I've fixed my issue. It's worked now

**Comment by mbrother2** [comment]
Hi all,

I will be close this issue here. Please open new ticket if you get any trouble when use butgg.bash or butgg.sh. Thank you!
