### ISSUE TITLE
MD5SUM Does not Same

### ISSUE THREAD

**Issue by burakbuylu** [mbrother2/backuptogoogle#11]
[ 13/12/2019 16:35:32 ] [CHECKS][FAIL] Can not verify md5 for file butgg.bash. Exit!

**Comment by mbrother2** [comment]
@burakbuylu 

Sorry, I updated md5sum for butgg.bash file. Please try again.

**Comment by mbrother2** [comment]
@burakbuylu 

Did you resolve your issue?
