### ISSUE TITLE
New: First time use

### ISSUE THREAD

**Issue by JL-HRC** [mbrother2/backuptogoogle#12]
##### Detail log:
1. I built & installed your app and am keen to use it. But I'm a bit new. 
It seemed to install fine and I wanted to run it. 
I went into the bin folder and tried to run cron, but it says "command not found".

2. How does the script know what to backup? must it be in /home/root/backup folder? 

root@PBS08:~/bin# ll
total 6536
drwxr-xr-x  2 root root    4096 Feb  4 05:52 ./
drwxr-xr-x 36 jan  jan     4096 Feb  4 05:36 ../
-rwxr-xr-x  1 root root   16626 Feb  4 05:35 butgg.bash*
-rwxr-xr-x  1 root root   16335 Feb  4 05:35 cron_backup.bash*
-rwxr-xr-x  1 root root 6644736 Feb  4 05:37 gdrive*
root@PBS08:~/bin# sh cron_backup.bash
cron_backup.bash: 170: cron_backup.bash: Syntax error: "(" unexpected
root@PBS08:~/bin# cron_backup.bash
cron_backup.bash: command not found
root@PBS08:~/bin# 

```
```

**Comment by mbrother2** [comment]
@JL-HRC 

Did you run command `source ${HOME}/.profile` after install butgg.bash ?

**Comment by JL-HRC** [comment]
No I did not.

**Comment by mbrother2** [comment]
@JL-HRC 

Please run above command before use butgg.bash. Remember butgg.bash use bash shell, not sh shell.

**Comment by JL-HRC** [comment]
Hi,
I've tried with my normal userid and also with root permission and I get this:
jan@PBS08:~$ ${HOME}/.profile
bash: /home/jan/.profile: Permission denied
jan@PBS08:~$ sudo bash
[sudo] password for jan: 
root@PBS08:~# ${HOME}/.profile
bash: /home/jan/.profile: Permission denied
root@PBS08:~#

**Comment by mbrother2** [comment]
Hi,

Please run:
```
source ${HOME}/.profile
```
NOT
```
${HOME}/.profile
```

P/S: You do not need root permission to run above command or use butgg.bash
