### ISSUE TITLE
exclude folder path

### ISSUE THREAD

**Issue by ghost** [mbrother2/backuptogoogle#13]
Hi i created one file in /root/.gdrive/exclude.list
and my backup path is : /opt/project

but i want to exclude /opt/project/cache folder
i try put to exclude.list 
cache
/opt/project/cache

but doesnt help how can exclude spesific folders ?

**Comment by mbrother2** [comment]
@bumblebeey 

Exclude feature is only added from butgg v1.3.0, if you use older version( see [CHANGE LOG](https://github.com/mbrother2/backuptogoogle/blob/master/CHANGLOG.md#butgg-130-02122019-new-feature)), it will be not working. Please try update butgg.bash with command `butgg.bash --update` then try again. If it's still not working, show output of the command `cron_backup.bash -v` then I will be check again.

**Comment by ghost** [comment]
i just install yesterday, backuptogoogle, what difference with butgg ?

**Comment by mbrother2** [comment]
They are the same, please show output of the command “cron_backup.bash -v”

**Comment by ghost** [comment]
here is the log:
------------------------------------------
exclude.list file content
/opt/project/cache
cache
-------------------------------------------

[ 18/02/2020 14:07:11 ] ---
[ 18/02/2020 14:07:11 ] Checking OS...
[ 18/02/2020 14:07:11 ] OS supported
[ 18/02/2020 14:07:12 ] Checking Google folder ID...
[ 18/02/2020 14:09:28 ] Check Google folder ID successful
[ 18/02/2020 14:09:28 ] Start sync to Google Drive...
[ 18/02/2020 14:09:28 ] Starting sync...
[ 18/02/2020 14:09:28 ] Collecting local and remote file information...
[ 18/02/2020 14:11:37 ] Found 118 local files and 117 remote files
[ 18/02/2020 14:11:38 ]
[ 18/02/2020 14:11:38 ] 1 remote files are missing
[ 18/02/2020 14:11:38 ] [0001/0001] Uploading cache/test.txt -> project/cache/test.txt
[ 18/02/2020 14:11:41 ] Sync finished in 13.539430297s
[ 18/02/2020 14:11:41 ] Finish! All files and directories in /opt/project are synced to Google Drive

**Comment by ghost** [comment]
what must be correct path in exclude.list file ? 
after backup folder(cache) or completly path(/opt/project/cache) ?
doesnt work both:)

in cron_backup.bash line 278
says file typle, its work only file type ? eg: .php etc ?

**Comment by mbrother2** [comment]
@bumblebeey 

You can not exclude file/directory when use SYNC method. You only use this feature when set SYNC_FILE=No in butgg.conf file.

**Comment by ghost** [comment]
I understand then can we add multiple backup path?

**Comment by mbrother2** [comment]
@bumblebeey,

Sorry, butgg.bash does not support multiple backup path now. Maybe this feature can be supported in the future.

**Comment by cduduc** [comment]
getting this:
root@ashbury1:/home/wuser/backuptogoogle# ./cron_backup.bash -v
[ 25/03/2020 14:02:43 ] ---
[ 25/03/2020 14:02:43 ] Checking OS...
[ 25/03/2020 14:02:43 ] OS supported
[ 25/03/2020 14:02:44 ] Start upload to Google Drive...
[ 25/03/2020 14:02:44 ] Checking Google folder ID...
[ 25/03/2020 14:02:44 ] Check Google folder ID successful
[ 25/03/2020 14:02:44 ] Directory 25_03_2020 existed. Skipping...
[ 25/03/2020 14:02:45 ] [INFO] You do not compress directory before upload
./cron_backup.bash: line 269: **realpath: command not found**
[ 25/03/2020 14:02:45 ] [CHECKS][FAIL] Can not detect file type for /build_gdrive_windows.bash. Exit

**Comment by mbrother2** [comment]
@cduduc 

Please follow here https://github.com/mbrother2/backuptogoogle/issues/15
