### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by mbrother2** [mbrother2/backuptogoogle#15]
getting this:
root@ashbury1:/home/wuser/backuptogoogle# ./cron_backup.bash -v
[ 25/03/2020 14:02:43 ] ---
[ 25/03/2020 14:02:43 ] Checking OS...
[ 25/03/2020 14:02:43 ] OS supported
[ 25/03/2020 14:02:44 ] Start upload to Google Drive...
[ 25/03/2020 14:02:44 ] Checking Google folder ID...
[ 25/03/2020 14:02:44 ] Check Google folder ID successful
[ 25/03/2020 14:02:44 ] Directory 25_03_2020 existed. Skipping...
[ 25/03/2020 14:02:45 ] [INFO] You do not compress directory before upload
./cron_backup.bash: line 269: **realpath: command not found**
[ 25/03/2020 14:02:45 ] [CHECKS][FAIL] Can not detect file type for /build_gdrive_windows.bash. Exit

_Originally posted by @cduduc in https://github.com/mbrother2/backuptogoogle/issues/13#issuecomment-603996773_

**Comment by mbrother2** [comment]
@cduduc,

Please show the output of these commands on your server:
```
cat /etc/os-release
md5sum $(which butgg.bash)
```

**Comment by cduduc** [comment]
root@ashbury1:/home/wuser# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
---------------------------------------------------------------------

root@ashbury1:/home/wuser/backuptogoogle# md5sum $(which butgg.bash)

returns nothing and hangs in there

root@ashbury1:/home/wuser/backuptogoogle# md5sum butgg.bash
f170064fdd3dc535737eb84b48bc28a6  butgg.bash

**Comment by mbrother2** [comment]
@cduduc 

Seem realpath is not the default package on Ubuntu 14. Please install it by command `apt-get install realpath` then try again.

P/S: I updated butgg.bash to install this package when setup in new version.

**Comment by cduduc** [comment]
Thank you, that solved it.

**Comment by mbrother2** [comment]
@cduduc 

You welcome :)
