### ISSUE TITLE
when put client id and secret i get error for google accounts list

### ISSUE THREAD

**Issue by rborges89** [mbrother2/backuptogoogle#16]
Error 400: redirect_uri_mismatch
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application 
![error](https://user-images.githubusercontent.com/44227668/81417734-e9d75700-914b-11ea-8fbb-e8b426efa526.png)

**Comment by mbrother2** [comment]
Hi @rborges89 

Please give me some informations about your server by run these commands:
```
cat /etc/os-release
cat ${HOME}/.gdrive/butgg.log
```

**Comment by rborges89** [comment]
hello thanks for reply:
here is the command information

**cat /etc/os-release**

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**cat ${HOME}/.gdrive/butgg.log**

[ 08/05/2020 14:35:15 ] ---
[ 08/05/2020 14:35:15 ] Creating necessary directory...
[ 08/05/2020 14:35:15 ] Create directory /root/.gdrive successful
[ 08/05/2020 14:35:15 ] Check write to /root/.gdrive successful
[ 08/05/2020 14:35:15 ] Create directory /root/bin successful
[ 08/05/2020 14:35:15 ] Check write to /root/bin successful
[ 08/05/2020 14:35:15 ] Checking OS...
[ 08/05/2020 14:35:15 ] OS supported
[ 08/05/2020 14:35:15 ] Checking necessary package...
[ 08/05/2020 14:35:15 ] Package curl is installed
[ 08/05/2020 14:35:15 ] Package realpath is installed
[ 08/05/2020 14:35:15 ] Package git is installed
[ 08/05/2020 14:35:15 ] Cheking network...
[ 08/05/2020 14:35:15 ] Connect Github successful
[ 08/05/2020 14:35:15 ] Connect Google successful
[ 08/05/2020 14:35:15 ] Downloading script cron file from github...
[ 08/05/2020 14:35:16 ] Check md5sum for file cron_backup.bash successful
[ 08/05/2020 14:35:16 ] Downloading setup file from github...
[ 08/05/2020 14:35:16 ] Check md5sum for file butgg.bash successful
[ 08/05/2020 14:35:16 ] Downloading go from Google...
[ 08/05/2020 14:35:20 ] Extracting go lang...
[ 08/05/2020 14:35:28 ] Cloning gdrive project from Github...
[ 08/05/2020 14:35:50 ] Build your own gdrive!
[ 08/05/2020 14:43:17 ] Building gdrive...
[ 08/05/2020 14:43:31 ] Build gdrive successful. Gdrive bin locate here /root/bin/gdrive
[ 08/05/2020 14:43:31 ] Setting up gdrive credential...
[ 08/05/2020 14:44:41 ] [WARNING] Can not create gdrive credential. Please run "/root/bin/gdrive about" to create it after

**Comment by rborges89** [comment]
Hello i fix the problem......It's not really a bug in your app
It happens that before I would upload my backups to google drive with a command implemented in symfony5 but when changing my database server from other place already instead of looking for my backups in the same VM I had to connect through ftp or ssh and I preferred to look for a script like yours that solved the problem for me, then,... the cient_id and client_secret that I was providing belonged to a web application and google in the error message told me that I needed to create one for a desktop application like yours so it did not return the Verification code.

Thank you very much, on the other hand have you thought about creating a Dockerfile for this project? and so it would be easier and more reusable.

**Comment by mbrother2** [comment]
@rborges89 

Thanks for your reply. Dockerfile or docker image on docker hub is good idea! Have you any ideas for this?

**Comment by mbrother2** [comment]
@rborges89 

I created new issue to tracking build backuptogoogle on docker. Please follow [here](https://github.com/mbrother2/backuptogoogle/issues/17)

**Comment by rborges89** [comment]
thanks for accepting the idea, I look at it right now.
Now it will be much better because the devops that have their environment in docker like me, could create a docker-compose where they have a container that creates the backup of the database and another container with the backuptogoogle docker that will automatically upload the copies to the Gdrive and in general we will be happier. great contribution
