### ISSUE TITLE
Error link request password for fist time

### ISSUE THREAD

**Issue by yohukm** [mbrother2/backuptogoogle#3]
Checking connectivity... done.
[ 17/11/2019 11:28:30 ] Build your own gdrive!
Please go to URL to create your own Google credential:
https://github.com/mbrother2/backuptogoogle/wiki/Create-own-Google-credential-step-by-step
 Your Google API client_id: 341513425591-XXXXXXXXXXXXXXXXXX.apps.googleusercontent.com341513425591-XXXXXXXXXXXXXXXXXX.apps.googleusercontent.com
 Your Google API client_secret: oLQr3eF8QKZH1FXXXXXXXXX
[ 17/11/2019 11:28:58 ] Building gdrive...
[ 17/11/2019 11:29:12 ] Build gdrive successful. Gdrive bin locate here /root/bin/gdrive
[ 17/11/2019 11:29:12 ] Setting up gdrive credential...
Authentication needed
Go to the following url in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=341513425591-XXXXXXXXXXXXXXXXX.apps.googleusercontent.com341513425591-XXXXXXXXXXXXXXXXX.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state

Enter verification code:

^C
root@localhost:~#
root@localhost:~# gdrive list
Authentication needed
Go to the following url in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=367116221053-XXXXXXXXXXXXXXXX.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state

Enter verification code:

i use control C to cancel  and 
run gdrive list  to get new link for  password request
after that all working fine

**Comment by mbrother2** [comment]
@yohukm 
Seem you have 2 gdrive bin on your server. Please show result of command:
```
for i in $(echo $PATH | sed 's/:/\n/g'); do echo "$i/"$(ls -1 $i | grep gdrive); done;
```

**Comment by yohukm** [comment]
> @yohukm
> Seem you have 2 gdrive bin on your server. Please show result of command:
> 
> ```
> for i in $(echo $PATH | sed 's/:/\n/g'); do echo "$i/"$(ls -1 $i | grep gdrive); done;
> ```

Nothing happen

**Comment by mbrother2** [comment]
Hmm, This is output on my server:
```
thanh1@ubuntu1804:~$ for i in $(echo $PATH | sed 's/:/\n/g'); do echo "$i/"$(ls -1 $i | grep gdrive); done;
/usr/local/sbin/
/usr/local/bin/
/usr/bin/
/sbin/
/bin/
/usr/games/
/usr/local/games/
/home/thanh1/bin/gdrive
```
Please check if gdrive bin is existed on above directorys. If you want to use gdrive which built by butgg.sh on a server which a gdrive bin is existed, you must call the absolute path of gdrive(on my case is /home/thanh1/bin/gdrive . Example: `/home/thanh1/bin/gdrive list`)

**Comment by yohukm** [comment]
root@localhost:~# for i in $(echo $PATH | sed 's/:/\n/g'); do echo "$i/"$(ls -1 $i | grep gdrive); done
/usr/local/sbin/
/usr/local/bin/gdrive
/usr/sbin/gdrive
/usr/bin/
/sbin/
/bin/
/usr/games/
/usr/local/games/
ls: cannot access '/snap/bin': No such file or directory
/snap/bin/

**Comment by mbrother2** [comment]
@yohukm 
As you see, you have two gdrive bin files locate at `/usr/local/bin` and `/usr/sbin/`. `butgg.bash` script do not use these files. It uses file locate at /root/bin or /home/$USER/bin. Juse remove or rename your exist gdrive bin files, everything will be ok. Example:
```
mv /usr/local/bin/gdrive /usr/local/bin/gdrive.bak
mv /usr/sbin/gdrive /usr/sbin/gdrive.bak
```
Then check again `which gdrive`
P/S: I have just update butgg.bash to support upload to specific diectory on Google Drive. You can try with follow command:
```
butgg.bash --update
butgg.bash --setup config
```
More details here:
https://github.com/mbrother2/backuptogoogle/blob/master/CHANGLOG.md
https://github.com/mbrother2/backuptogoogle/wiki/Get-Google-folder-ID

**Comment by mbrother2** [comment]
@yohukm 
Do you resolve your issue?
