### ISSUE TITLE
Script for Windows version of the gdrive

### ISSUE THREAD

**Issue by wasanthakj** [mbrother2/backuptogoogle#5]
##### Detail log:
I am using the Windows version of the gdrive utility, a Windows version of this script will be quite helpful (ref: the issue logged in gdrive for getting failures with 400 error).

**Comment by mbrother2** [comment]
@wasanthakj 

I will be write Script for Windows 10 asap.

**Comment by wasanthakj** [comment]
Thank you @mbrother2 , looking forward to try it out.

**Comment by mbrother2** [comment]
@wasanthakj 

I wrote a script to build gdrive on Windows x86_64. Please try with 2 steps:
1. Install git for windows https://git-scm.com/download/win
2. Build gdrive on Git bash terminal:
```
curl -o build_gdrive_windows.bash https://raw.githubusercontent.com/mbrother2/backuptogoogle/master/build_gdrive_windows.bash
bash build_gdrive_windows.bash
```

**Comment by wasanthakj** [comment]
@mbrother2 
I followed the instructions to build the gdrive.exe on Windows and it was ok, however when I try to run it I get the following error, hope you can help to get around this, thank you.

C:\Users\Wasan\gdrive>gdrive list
Failed to list files: Get https://www.googleapis.com/drive/v3/files?alt=json&fields=nextPageToken%2Cfiles%28id%2Cname%2Cmd5Checksum%2CmimeType%2Csize%2CcreatedTime%2Cparents%29&orderBy=&pageSize=30&q=trashed+%3D+false+and+%27me%27+in+owners: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

**Comment by mbrother2** [comment]
@wasanthakj

Try to remove old token and create new with command `gdrive.exe about`

**Comment by wasanthakj** [comment]
It worked!! thanks so much @mbrother2 .

**Comment by mbrother2** [comment]
@wasanthakj 

You welcome :)
