### ISSUE TITLE
Add file/folder exclusion

### ISSUE THREAD

**Issue by mwarner416** [mbrother2/backuptogoogle#8]
Could you add file/folder exclusion.

**Comment by mbrother2** [comment]
@mwarner416 

New feature for excluding file/directory will come soon.

**Comment by mbrother2** [comment]
@mwarner416 

I added new  feature for excluding file/directory. Please update your cron_backup.bash and add file/directory name which you want to exclude to file `${HOME}/.gdrive/exclude.list`

#### Update script
```
butgg.bash --update
```
#### Example
- exclude.list file
```
thanh4@ubuntu1804:~/bin$ cat ${HOME}/.gdrive/exclude.list
backup1
backup2.txt
```
- Run test cron backup
```
thanh4@ubuntu1804:~/bin$ cron_backup.bash -v
[ 02/12/2019 01:45:22 ] ---
[ 02/12/2019 01:45:22 ] Checking OS...
[ 02/12/2019 01:45:22 ] OS supported
[ 02/12/2019 01:45:22 ] Start upload to Google Drive...
[ 02/12/2019 01:45:23 ] Directory 02_12_2019 existed. Skipping...
[ 02/12/2019 01:45:24 ] [INFO] Directory backup1 in list exclude. Skip upload
[ 02/12/2019 01:45:24 ] Uploading file /home/thanh4/backup/backup1.txt to directory 02_12_2019...
[ 02/12/2019 01:45:26 ] [UPLOAD] Uploaded file /home/thanh4/backup/backup1.txt to directory 02_12_2019
[ 02/12/2019 01:45:26 ] Uploading directory /home/thanh4/backup/backup2 to directory 02_12_2019...
[ 02/12/2019 01:45:27 ] [UPLOAD] Uploaded directory /home/thanh4/backup/backup2 to directory 02_12_2019
[ 02/12/2019 01:45:27 ] [INFO] File backup2.txt in list exclude. Skip upload
[ 02/12/2019 01:45:27 ] Finish! All files and directories in /home/thanh4/backup are uploaded to Google Drive in directory 02_12_2019
[ 02/12/2019 01:45:28 ] Directory 25_11_2019 does not exist. Nothing need remove!
```

**Comment by mwarner416** [comment]
Well I deleted everything in my google drive and went to re-sync but ended up with this.

[ 02/12/2019 18:49:12 ] ---
[ 02/12/2019 18:49:12 ] Checking OS...
[ 02/12/2019 18:49:12 ] OS supported
[ 02/12/2019 18:49:12 ] Start upload to Google Drive...
[ 02/12/2019 18:49:13 ] Directory 02_12_2019 existed. Skipping...
[ 02/12/2019 18:49:13 ] Finish! All files and directories in /mnt/Storage/backups are uploaded to Google Drive in directory 02_12_2019
[ 02/12/2019 18:49:13 ] Directory 29_11_2019 does not exist. Nothing need remove!

**Comment by mbrother2** [comment]
@mwarner416 

Seem nothing in /mnt/Storage/backups directory. Please show the output of command `ls -al /mnt/Storage/backups`

**Comment by mbrother2** [comment]
@mwarner416 

Very sorry, my mistake. My script will not upload to Google Drive if file exclude.list does not exist. I fixed it in newest version. Please update butgg.bash and try again.

**Comment by mwarner416** [comment]
It works.

Just so you know I modified two things in your setup and it install and runs like a champ on fedora.

I changed the delimiter in the os check to '=' and changed CentOS to Fedora.  Fedora will convert yum commands to dnf.

**Comment by mbrother2** [comment]
@mwarner416 

Good work. Close issue here.
